//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analizis
    {
        public int ObjectNmoblesId { get; set; }
        public string Title { get; set; }
        public Nullable<double> Lng { get; set; }
        public Nullable<double> Lat { get; set; }
        public string TypeId { get; set; }
        public string AddressStreet { get; set; }
        public string AddressHouse { get; set; }
        public string AddressNumber { get; set; }
        public Nullable<int> idCity { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<int> IsBuy { get; set; }
        public int BuyClient { get; set; }
        public int BuyRealtorId { get; set; }
        public int PayClientId { get; set; }
        public int PayRialtorId { get; set; }
        public int Price { get; set; }
        public Nullable<decimal> PriceCompany { get; set; }
        public string NamePayClient { get; set; }
        public string NameBuyClient { get; set; }
        public string NamePayRealtor { get; set; }
        public string NamBuyRealtor { get; set; }
        public Nullable<decimal> ClientShare { get; set; }
        public Nullable<decimal> BuyRieltorShare { get; set; }
        public Nullable<decimal> PayRieltorShare { get; set; }
    }
}
