//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demand()
        {
            this.DemandApartments = new HashSet<DemandApartments>();
            this.DemandHouse = new HashSet<DemandHouse>();
            this.DemandLand = new HashSet<DemandLand>();
        }
    
        public int id { get; set; }
        public int MinPrice { get; set; }
        public int MaxPrice { get; set; }
        public int RealtorId { get; set; }
        public int ClientId { get; set; }
        public string TypeDemand { get; set; }
        public Nullable<int> AddressCity { get; set; }
        public string AddressStreet { get; set; }
        public string AddressHouse { get; set; }
        public string AddressNumber { get; set; }
    
        public virtual City City { get; set; }
        public virtual Client Client { get; set; }
        public virtual Realtor Realtor { get; set; }
        public virtual TypeObjectNmobles TypeObjectNmobles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandApartments> DemandApartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandHouse> DemandHouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandLand> DemandLand { get; set; }
    }
}
