//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realtor
    {
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MidlName { get; set; }
        public Nullable<int> share { get; set; }
        public int idUser { get; set; }
        public int id { get; set; }
    
        public virtual User User { get; set; }
    }
}
