//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplies
    {
        public int id { get; set; }
        public int Price { get; set; }
        public int RialtorId { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> ObjectNmobles { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ObjectNmobles ObjectNmobles1 { get; set; }
        public virtual Realtor Realtor { get; set; }
    }
}
